# Location of your mips gcc
N64CHAIN := C:/n64/gcc-toolchain-mips64-win64
# Location of your N64 SDK
SDK := C:/n64/n64sdk
# Python command, e.g. python3 (or location if not on the path)
PYTHON := python
