COMPONENT(Position, Vec3)
COMPONENT(Velocity, Vec3)
COMPONENT(Collision, BVHTree*)
COMPONENT(Collider, struct {})
COMPONENT(Rotation, Vec3s)
COMPONENT(Behavior, BehaviorParams)
COMPONENT(Model, Model*)
COMPONENT(AnimState, AnimState)
COMPONENT(Gravity, GravityParams)
