#ifndef __SURFACE_TYPES_H__
#define __SURFACE_TYPES_H__

#define SURFACE_NONE 0
#define SURFACE_DEFAULT 1
#define SURFACE_SLOW 2
#define SURFACE_HARD 3
#define SURFACE_DEATH_PLANE 4
#define SURFACE_TTM_VINES 5

#endif
